insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '1', '0110', '一般贸易', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '2', '0615', '进料对口', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '3', '0654', '进料深加工', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '4', '0715', '进料非对口', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '5', '3010', '货样广告品', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '6', '0664', '进料料件复出', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '7', '4600', '进料成品退换', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '8', '0214', '来料加工', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '9', '1300', '修理物品', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '10', '9900', '其他', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '11', '0657', '进料余料结转', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '12', '4561', '退运货物', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '13', '4500', '直接退运', null);
insert into `trade_way_do` ( `id`, `code`, `cn`, `en`) values ( '14', '3422', '对外承包出口', null);


insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '1', 'USD', '美元', 'US Dollar');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '2', 'IDR', '印度尼西亚卢比', 'Rupiah');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '3', 'JPY', '日本元', 'Yen');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '4', 'MOP', '澳门元', 'Pataca');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '5', 'MYR', '马来西亚林吉特', 'Malaysian Ringgit');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '6', 'PHP', '菲律宾比索', 'Philippine Piso');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '7', 'SGD', '新加坡元', 'Singapore Dollar');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '8', 'KRW', '韩国圆', 'Won');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '9', 'THB', '泰国铢', 'Baht');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '10', 'RMB', '人民币', 'Yuan Renminbi');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '11', 'TWD', '新台币', 'New Taiwan Dollar');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '12', 'EUR', '欧元', 'Euro');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '13', 'DKK', '丹麦克朗', 'Danish Krone');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '14', 'GBP', '英镑', 'Pound Sterling');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '15', 'NOK', '挪威克朗', 'Norwegian Krone');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '16', 'SEK', '瑞典克朗', 'Swedish Krona');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '17', 'CHF', '瑞士法郎', 'Swiss Franc');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '18', 'RUB', '俄罗斯卢布', 'Russian Ruble');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '19', 'CAD', '加拿大元', 'Canadian Dollar');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '20', 'HKD', '港币', 'Hong Kong Dollar');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '21', 'AUD', '澳大利亚元', 'Australian Dollar');
insert into `money_do` ( `id`, `code`, `cn`, `en`) values ( '22', 'NZD', '新西兰元', 'New Zealand Dollar');
